---

- name: "Restart ssh"
  service:
    name: "ssh"
    state: "restarted"

- name: "Restart ufw"
  service:
    name: "ufw"
    state: "restarted"

- name: "Restart server"
  command: /sbin/reboot
