root_password: !vault |
          PLACE HERE THE CONTENTS OF ansible-vault encrypt_string

deploy_user_password: !vault |
          PLACE HERE THE CONTENTS OF ansible-vault encrypt_string

privatekey_passphrase: !vault |
          PLACE HERE THE CONTENTS OF ansible-vault encrypt_string

deploy_user_username: "douglas"

common_packages:
  - htop
