services:
  caddy:
    image: caddy:2-alpine
    environment:
      DOMAIN_NAME: http://localhost
    ports:
      - "80:80"
    volumes:
      - ./media-root-local/:/srv/media
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data: {}
  caddy_config: {}
