---

# Check also: ./ufw-basics.yml, ./docker/ufw-rules-for-docker.yml

- name: "Change root password"
  user:
    name: "root"
    password: "{{ '%s' | format(root_password) | password_hash('sha512') }}"

# Variables: {{ deploy_user_username }} {{ deploy_user_password }}
# {{ deploy_user_password }}: It's important to use Ansible Vault to store secrets.
# So if you can, please do.
- name: "Create main user group"
  group:
    name: "{{ deploy_user_username }}"

- name: "Create main user"
  user:
    name: "{{ deploy_user_username }}"
    shell: "/bin/bash"
    password: "{{ '%s' | format(deploy_user_password) | password_hash('sha512') }}"
    groups:
      - "{{ deploy_user_username }}"


# -----------
# You will probably create your new user while being root.
# If your root user already has your public key in authorized_keys
# You can copy to your new user, so you can login with your public key:

- name: "Ensure .ssh dir for our new user is present"
  file:
    state: "directory"
    path: /home/{{ deploy_user_username }}/.ssh/
    owner: "{{ deploy_user_username }}"
    group: "{{ deploy_user_username }}"
    mode: 0700

- name: "Copy authorized_keys from root to new user"
  copy:
    remote_src: yes
    src: "/root/.ssh/authorized_keys"
    dest: "/home/{{ deploy_user_username }}/.ssh/authorized_keys"
    owner: "{{ deploy_user_username }}"
    group: "{{ deploy_user_username }}"
    mode: 0600


# -----------
# Better security for SSH access
- name: "Disallow password authentication"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: "present"
  notify: "Restart ssh"

- name: "Disallow root SSH access"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: "present"
  notify: "Restart ssh"
