version: "3.7"

services:
  caddy:
    image: douglasmiranda/caddy
    volumes:
      - ./caddy/:/etc/caddy/
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider http://localhost:7777 || exit 1"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 40s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        failure_action: rollback
    ports:
      - "80:80"
      # You don't need to expose this
      # this is so you can check on your host
      - "7777:7777"
